=encoding utf8


This is Perl module B<App::Rolling>.

=begin html

<a href="http://travis-ci.org/bayashi/App-Rolling"><img src="https://secure.travis-ci.org/bayashi/App-Rolling.png"/></a>

=end html


=head1 INSTALLATION

App::Rolling installation is straightforward. If your CPAN shell is set up,
you should just be able to do

    % cpan App::Rolling

Download it, unpack it, then build it as per the usual:

    % perl Makefile.PL
    % make && make test

Then install it:

    % make install


=head1 DOCUMENTATION

App::Rolling documentation is available as in POD. So you can do:

    % perldoc App::Rolling


=head1 REPOSITORY

App::Rolling is hosted on github
L<http://github.com/bayashi/App-Rolling>


=head1 LICENSE

This module is free software; you can redistribute it and/or
modify it under the same terms as Perl itself. See L<perlartistic>.


=head1 AUTHOR

Dai Okabayashi E<lt>bayashi@cpan.orgE<gt>
